FirstMVC/Controllers/FilterController.cs
using FirstMVC.Filters;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstMVC.Controllers
{
    public class FilterController : Controller
    {
        //_____________________________AUTHENTICATION FILTER________________________________________________

        [AuthenticationFilters] //First it check the authentication..if true comes here else goes to home.
        public ActionResult AuthenticationFilter(string id)
        {
            Debug.WriteLine("dddddddddddd");
            return View("../Student/Department");
        }




        [OutputCache] //this filter invokes ActionFilterAttribute class which further implements IActionFilter & IResultFilter
        [Authorize] //this filter invokes OnAuthorization 
        [HandleError] //implements iException Filter...
        public ActionResult Contact2(int? id, string id1) //url for this can be controller/Contact/hello/world .....so here id = null as it acepts string and id1 = world 
        {
            return null;
        }


        //)__________________________________________ACTION FILTER________________________________________________________

        //....Before Action and then after action and then VIEW..

        [ActionFiltera]
        public ActionResult ActionFiltera(string id)
        {
            Debug.WriteLine("dddddddddddd");
            return View("../Student/Department");
        }

        //___________________________________________RESULT FILTER__________________________________________________________
        //
        // RESULT FILTER :: OnResultExecuting is invoked Before the VIEW () OnResultExecuted is invoked and After the VIEW.............
        //
        [ResultFIler]
        public ActionResult ResultFilter(string id)
        {
            Debug.WriteLine("dddddddddddd");
            return View("../Student/Department");
        }



        //________________________________EXCEPTION FILTER_________________________________________________________
        //
        // The moment exception is encountered, it calls the ExceptionFilter class and returns the Respecive Error View Page
        // and it doesnt return back...
        [ExceptionFilters]
        public ActionResult Exception(string id)
        {
            int a = 1;
            int b = 1;
            Debug.WriteLine(HttpContext.Session.SessionID);
            var k = 1 / (a - b);
            Debug.WriteLine("DDD");
            return View("../Student/Department");
        }

    }
}

FirstMVC/Controllers/ValidationController.cs
using FirstMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstMVC.Controllers
{
    public class ValidationController : Controller
    {
        //______________________CLIENT SIDE VALIDATION ___________________________________________________________________

        [HttpPost]
        public ActionResult ClientSideValidation()
        {
            if (ModelState.IsValid)
            {
                ClientValidation emp = new ClientValidation();
                UpdateModel(emp);
                ViewBag.emp1 = emp;
                return View(emp);
            }

            return View();
        }


        //Vlidating one field with JSON true or False
        [HttpPost]
        public ActionResult validationOfOneFiled(string username)
        {
            if (username.Any(char.IsDigit))
            {
                return Json(false);
            }
            return Json(true);
        }





        //______________________SERVER SIDE VALIDATION ___________________________________________________________________


        public ActionResult ServerSideValidation31(string s)
        {
            Debug.WriteLine("HttpGet Server");
            return View("../Filter/ServerSideValidation");
        }

        [HttpPost]
        public ActionResult ServerSideValidation321(ServerValidation sv)
        {
            Debug.WriteLine("Came to post validation" + Request["username"]);
            Dictionary<string, string> errDict = new Dictionary<string, string>();
            if (Request["username"] == "")
            {
                Debug.WriteLine("Came to verify username server side validation");
                errDict.Add("username", "Username cannot be null"); // here the TryGetValue  tries to get the value

            }
            ViewBag.errDict = errDict;
            return View("../Filter/ServerSideValidation");
        }


      


    }
}

FirstMVC/Views/Filter/ServerSideValidation.cshtml
@{
    ViewBag.Title = "Home Page";
}
@using FirstMVC.Models;
@model FirstMVC.Models.ServerValidation

@{
    if (Model != null)
    {
            @: username @Model.username; <br/>
            @: gender : @Model.gender; <br/>
            @: Password @Model.password; <br/>
            @: Confirm password :@Model.password; </br>
            @: Accept : @Model.accept; <br/>
            @: Country : @Model.countries;
            
            @Html.Partial("_HtmlHelper");  @*For Partial View*@

    
}
}


<div class="jumbotron">
    <strong>ASP.NET MVC</strong>
</div>

<tr class="form-group">
    @using (Html.BeginForm("ServerSideValidation321", "Validation", FormMethod.Post))
    {

        <table>
            <tr>
                <td>@Html.LabelFor(x => x.username)</td>
                <td>@Html.TextBoxFor(x => x.username)</td>
                <td>
                    @{
                        if (ViewBag.errDict != null)
                        {
                            string err;
                          // if (ViewBag.errDict.TryGetValue("username", out err))
                           if (ViewBag.errDict.ContainsKey("username"))
                            {
                                    err = ViewBag.errDict["username"];
                              <span  class ="field-validation-error"> @err
                              </span>
                            }
                        }
                     }
                            </td>
               

            </tr>
            <tr>
                <td>@Html.LabelFor(x => x.password)</td>
                <td>@Html.PasswordFor(x => x.password)</td>
                <td></td>

            </tr>

            <tr>
                <td>@Html.LabelFor(x => x.confirm_password)</td>
                <td>@Html.PasswordFor(x => x.confirm_password)</td>
                <td></td>
                
            </tr>

            <tr>
                <td>@Html.LabelFor(x => x.countries)</td>
                <td>
                    @{
                        List<SelectListItem> listItems = new List<SelectListItem>();
                        listItems.Add(new SelectListItem { Text = "china", Value = "China" });
                        listItems.Add(new SelectListItem { Text = "India", Value = "India"});
                        listItems.Add(new SelectListItem { Text = "Brazil", Value = "Brazil" });

                    }
                   @Html.DropDownListFor(x => x.countries, listItems, "Selct Countries")
                </td>
                <td>
                    @Html.DropDownListFor(x => x.countries, new List<SelectListItem> {
                       new SelectListItem { Text = "china", Value = "China" },
                       new SelectListItem { Text = "India", Value = "India"},
                       new SelectListItem { Text = "Brazil", Value = "Brazil" }
                       },"Select Countries")
                </td>

            </tr>


            <tr>
                <td>@Html.LabelFor(x => x.gender)</td>
                <td>
                    @Html.RadioButtonFor(x => x.gender, "M", new { id = "male" }) Male
                    &nbsp;
                    @Html.RadioButtonFor(x => x.gender, "F", new { id = "female" }) Female
                </td>
                <td>
                   
                </td>

            </tr>

            <tr>
                <td>@Html.LabelFor(x => x.accept)</td>
                <td>@Html.CheckBoxFor(x => x.accept)</td>

                <td></td>

            </tr>

            <tr>

                <td colspan="3"><input type="submit" value="Register"</td>

            </tr>

        </table>
    }